version: '2'
services:
  db:
    build: ./docker/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_server
    volumes:
      - ./docker/db_data:/var/lib/mysql
  php:
    build: ./docker/php
    ports:
      - '9080:80'
    volumes:
      - ./laravel-server:/var/www/html
    depends_on:
      - db